name: mlp
description: "Multilayer perceptron package that allows to create machine learning model"
version: 0.0.4
homepage: https://github.com/MURABIT-PASHA/dart-mlp

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


test_data:
  - description: "ARFF FILE"
    path: assets/penguins.arff

  - description: "CSV FILE"
    path: assets/penguins.csv

flutter:
  assets:
    - assets/penguins.arff
    - assets/penguins.csv